version: '3.7'

volumes:
  lognetwork.com:
  peer0.logprovider.lognetwork.com:
  peer1.logprovider.lognetwork.com:
  peer0.logauditor.lognetwork.com:
  peer1.logauditor.lognetwork.com:

networks:
  lognetwork:
    name: lognetwork

services:
  orderer.lognetwork.com:
    container_name: orderer.lognetwork.com
    image: hyperledger/fabric-orderer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/etc/hyperledger/fabric/genesisblock
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - /home/raul/tesis-blockchain/crypto/ordererOrganizations/lognetwork.com/orderers/orderer.lognetwork.com/msp:/var/hyperledger/orderer/msp
      - /home/raul/tesis-blockchain/crypto/ordererOrganizations/lognetwork.com/orderers/orderer.lognetwork.com/tls:/var/hyperledger/orderer/tls
      - /home/raul/tesis-blockchain/config/orderer.genesis.block:/etc/hyperledger/fabric/genesisblock
      - lognetwork.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - lognetwork

  ca.logprovider.lognetwork.com:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-logprovider
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
    ports:
      - "7054:7054"
      - "9444:9444"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/raul/tesis-blockchain/crypto/peerOrganizations/logprovider.lognetwork.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.logprovider.lognetwork.com
    networks:
      - lognetwork

  couchdb0.logprovider:
    container_name: couchdb0.logprovider
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - lognetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  peer0.logprovider.lognetwork.com:
    container_name: peer0.logprovider.lognetwork.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lognetwork
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIES=3
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP=10
      - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=35s
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.logprovider.lognetwork.com
      - CORE_PEER_ADDRESS=peer0.logprovider.lognetwork.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.logprovider.lognetwork.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.logprovider.lognetwork.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.logprovider.lognetwork.com:7051
      - CORE_PEER_LOCALMSPID=LogProviderMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.logprovider.lognetwork.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0logprovider"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.logprovider:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /home/raul/tesis-blockchain/config/peercfg:/etc/hyperledger/peercfg
      - /home/raul/tesis-blockchain/crypto/peerOrganizations/logprovider.lognetwork.com/peers/peer0.logprovider.lognetwork.com:/etc/hyperledger/fabric
      - peer0.logprovider.lognetwork.com:/var/hyperledger/production
      - /var/run/:/host/var/run/
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9445:9445
    networks:
      - lognetwork
    depends_on:
      couchdb0.logprovider:
        condition: service_healthy

  couchdb1.logprovider:
    container_name: couchdb1.logprovider
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "6984:5984"
    networks:
      - lognetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  peer1.logprovider.lognetwork.com:
    container_name: peer1.logprovider.lognetwork.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lognetwork
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIES=3
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP=10
      - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=35s
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.logprovider.lognetwork.com
      - CORE_PEER_ADDRESS=peer1.logprovider.lognetwork.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.logprovider.lognetwork.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.logprovider.lognetwork.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.logprovider.lognetwork.com:8051
      - CORE_PEER_LOCALMSPID=LogProviderMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.logprovider.lognetwork.com:9446
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1logprovider"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.logprovider:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /home/raul/tesis-blockchain/config/peercfg:/etc/hyperledger/peercfg
      - /home/raul/tesis-blockchain/crypto/peerOrganizations/logprovider.lognetwork.com/peers/peer1.logprovider.lognetwork.com:/etc/hyperledger/fabric
      - peer1.logprovider.lognetwork.com:/var/hyperledger/production
      - /var/run/:/host/var/run/
    working_dir: /root
    command: peer node start
    ports:
      - 8051:8051
      - 9446:9446
    networks:
      - lognetwork
    depends_on:
      couchdb1.logprovider:
        condition: service_healthy

  ca.logauditor.lognetwork.com:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-logauditor
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:9447
    ports:
      - "8054:8054"
      - "9447:9447"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/raul/tesis-blockchain/crypto/peerOrganizations/logauditor.lognetwork.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.logauditor.lognetwork.com
    networks:
      - lognetwork

  couchdb0.logauditor:
    container_name: couchdb0.logauditor
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - lognetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  peer0.logauditor.lognetwork.com:
    container_name: peer0.logauditor.lognetwork.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lognetwork
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIES=3
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP=10
      - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=35s
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.logauditor.lognetwork.com
      - CORE_PEER_ADDRESS=peer0.logauditor.lognetwork.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.logauditor.lognetwork.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.logauditor.lognetwork.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.logauditor.lognetwork.com:9051
      - CORE_PEER_LOCALMSPID=LogAuditorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.logauditor.lognetwork.com:9448
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0logauditor"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.logauditor:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /home/raul/tesis-blockchain/config/peercfg:/etc/hyperledger/peercfg
      - /home/raul/tesis-blockchain/crypto/peerOrganizations/logauditor.lognetwork.com/peers/peer0.logauditor.lognetwork.com:/etc/hyperledger/fabric
      - peer0.logauditor.lognetwork.com:/var/hyperledger/production
      - /var/run/:/host/var/run/
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9448:9448
    networks:
      - lognetwork
    depends_on:
      couchdb0.logauditor:
        condition: service_healthy

  couchdb1.logauditor:
    container_name: couchdb1.logauditor
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    networks:
      - lognetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  peer1.logauditor.lognetwork.com:
    container_name: peer1.logauditor.lognetwork.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lognetwork
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIES=3
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP=10
      - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=35s
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.logauditor.lognetwork.com
      - CORE_PEER_ADDRESS=peer1.logauditor.lognetwork.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.logauditor.lognetwork.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.logauditor.lognetwork.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.logauditor.lognetwork.com:10051
      - CORE_PEER_LOCALMSPID=LogAuditorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.logauditor.lognetwork.com:9449
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1logauditor"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.logauditor:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /home/raul/tesis-blockchain/config/peercfg:/etc/hyperledger/peercfg
      - /home/raul/tesis-blockchain/crypto/peerOrganizations/logauditor.lognetwork.com/peers/peer1.logauditor.lognetwork.com:/etc/hyperledger/fabric
      - peer1.logauditor.lognetwork.com:/var/hyperledger/production
      - /var/run/:/host/var/run/
    working_dir: /root
    command: peer node start
    ports:
      - 10051:10051
      - 9449:9449
    networks:
      - lognetwork
    depends_on:
      couchdb1.logauditor:
        condition: service_healthy

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.logprovider.lognetwork.com:7051
      - CORE_PEER_LOCALMSPID=LogProviderMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/logprovider.lognetwork.com/peers/peer0.logprovider.lognetwork.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/logprovider.lognetwork.com/peers/peer0.logprovider.lognetwork.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/logprovider.lognetwork.com/peers/peer0.logprovider.lognetwork.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/logprovider.lognetwork.com/users/Admin@logprovider.lognetwork.com/msp
      - CHANNEL_NAME=security-logs-channel
      - CHAINCODE_NAME=LogManager
      - CC_SRC_PATH=/opt/gopath/src/chaincode/logmanager/
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:2.5
      - CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:2.5
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/lognetwork.com/tlsca/tlsca.lognetwork.com-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /home/raul/tesis-blockchain/chaincode/:/opt/gopath/src/chaincode/
      - /home/raul/tesis-blockchain/crypto:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - /home/raul/tesis-blockchain/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - /home/raul/tesis-blockchain/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.lognetwork.com
      - peer0.logprovider.lognetwork.com
      - peer1.logprovider.lognetwork.com
      - peer0.logauditor.lognetwork.com
      - peer1.logauditor.lognetwork.com
    networks:
      - lognetwork
