# core.yaml - Configuración del peer para Fabric 2.5
# SOLUCIÓN al problema de chaincode externo

# Configuración del peer
peer:
  authentication:
    timewindow: 15m0s

  id: peer0.logprovider.lognetwork.com
  networkId: lognetwork

  # Configuración de direcciones
  address: 0.0.0.0:7051
  addressAutoDetect: false

  # Configuración de Gossip
  gossip:
    bootstrap: peer0.logprovider.lognetwork.com:7051
    useLeaderElection: true
    orgLeader: false

  # Configuración TLS
  tls:
    enabled: true
    cert:
      file: /etc/hyperledger/fabric/tls/server.crt
    key:
      file: /etc/hyperledger/fabric/tls/server.key
    rootcert:
      file: /etc/hyperledger/fabric/tls/ca.crt
    clientAuthRequired: false

  # Configuración de la base de datos
  state:
    stateDatabase: CouchDB
    couchDBConfig:
      couchDBAddress: couchdb0.logprovider:5984
      username: admin
      password: adminpw

  # Configuración de archivos
  fileSystemPath: /var/hyperledger/production

  # Configuración MSP
  mspConfigPath: /etc/hyperledger/fabric/msp
  localMspId: LogProviderMSP

  # Configuración BCCSP (Blockchain Crypto Service Provider)
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256

# Configuración de chaincode - CLAVE PARA SOLUCIONAR EL PROBLEMA
chaincode:
  # Configuración del builder de chaincode
  builder: hyperledger/fabric-ccenv:2.5
  pull: false

  # Runtime para diferentes lenguajes
  golang:
    runtime: hyperledger/fabric-baseos:2.5
    dynamicLink: false
  node:
    runtime: hyperledger/fabric-nodeenv:2.5
  java:
    runtime: hyperledger/fabric-javaenv:2.5

  # Configuraciones críticas para evitar el builder externo
  mode: net
  keepalive: 0
  startuptimeout: 300s
  executetimeout: 30s
  installTimeout: 300s

  # Configuración para chaincodes del sistema
  system:
    cscc: enable
    lscc: enable
    escc: enable
    vscc: enable
    qscc: enable

  # Configuración de logging
  logging:
    spec: INFO

# Configuración de VM
vm:
  endpoint: unix:///host/var/run/docker.sock
  docker:
    tls:
      enabled: false
    attachStdout: false
    hostConfig:
      NetworkMode: lognetwork
      LogConfig:
        Type: json-file
        Config:
          max-size: "50m"
          max-file: "5"
      Memory: 2147483648

# Configuración de logging
logging:
  spec: INFO

# Configuración de métricas
metrics:
  provider: disabled

# Configuración de operaciones
operations:
  listenAddress: 0.0.0.0:9445
  tls:
    enabled: false